spring:
  security:
    user:
      name: user
      password: user
    oauth2:
      client:
        registration:
          google:
            userinfo-endpoint: https://openidconnect.googleapis.com/v1/userinfo
          kakao:
            userinfo-endpoint: https://kapi.kakao.com/v2/user/me
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-valid-time-in-seconds: 86400
logging:
  level:
    com:
      pencilwith: DEBUG
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    path: ./log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  charset:
    file: UTF-8
    console: UTF-8
server:
  port: 5000
cloud:
  aws:
    s3:
      bucket: com.pencil-with
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
