spring:
  datasource:
    url: jdbc:mysql://pencil.ccrcrtneqrew.ap-northeast-2.rds.amazonaws.com:3306/pencil?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
#      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true