spring:
  security:
    user:
      name: user
      password: user
    oauth2:
      client:
        registration:
          google:
            userinfo-endpoint: https://openidconnect.googleapis.com/v1/userinfo
          kakao:
            userinfo-endpoint: https://kapi.kakao.com/v2/user/me
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-valid-time-in-seconds: 86400
logging:
  level:
    com:
      pencilwith: DEBUG
server:
  port: 5000
