spring:
  datasource:
    url: jdbc:h2:mem:pencilwith
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            userinfo-endpoint: https://openidconnect.googleapis.com/v1/userinfo
          kakao:
            userinfo-endpoint: https://kapi.kakao.com/v2/user/me

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com:
      pencilwith: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-valid-time-in-seconds: 86400